env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
plugins:
  - react
  - prettier
rules: {
  prettier/prettier: "error",
  react/react-in-jsx-scope: 0,
}
